Rename whohacks to whois.
hspsh/whohacks pull request #79
Opened 2024-09-29 18:24 UTC by EduKav1813

The project is named "whohacks" while the actual
folder is named "whois", which causes `poetry
install` to fail.

2024-09-29 18:27 UTC, not7cd requested changes
I think there should be a different setting for changing the module name that is being found by poetry.

2024-09-30 09:28 UTC, EduKav1813 commented
Ok, I will have a look

2024-10-01 18:20 UTC, EduKav1813 commented
I managed to fix this problem by using the "packages" section and modifying the Dockerfile. I also moved from using the deprecated `poetry install --no-dev` to newer `poetry install --only main.`

2024-10-07 07:51 UTC, not7cd commented on Dockerfile
> +COPY whois /app/whois/
You shouldn't be required to do this. We are not copying project files before requirement install, so every code change doesn't force requirement installation.

2024-10-23 18:36 UTC, EduKav1813 commented
Closed in favor of https://github.com/hspsh/whohacks/pull/81

2024-10-23 18:36 UTC, closed without merging