Migrate db to sqlalchemy
hspsh/whohacks pull request #83
Opened 2024-11-05 21:40 UTC by EduKav1813

2024-11-06 18:36 UTC, not7cd requested changes

2024-11-06 18:36 UTC, not7cd commented on whois/web.py
> +    recent = filter_recent(timedelta(**settings.recent_time), devices)
I would prefer to keep `get_recent` in `device_repository`

2024-11-06 18:36 UTC, not7cd commented on whois/web.py
> +        mine = filter(lambda device: device.owner == current_user.get_id(), devices)
it this not possible to keep this logic within `current_user`

2024-11-06 18:36 UTC, not7cd commented on whois/settings_test.py
why is this file needed?

2024-11-10 21:05 UTC, EduKav1813 commented on whois/settings_test.py
This file indeed was not used at the moment and removed. I t was planned to have multiple configurations for the app. This functionality was implemented here -> 32d9f54af0eef7718e3ac713152442e32eae52b4

2024-11-12 20:33 UTC, EduKav1813 commented on whois/web.py
> +        mine = filter(lambda device: device.owner == current_user.get_id(), devices)
I am not sure if it's fully possible like the old way, but as a compromise I implemented this fetch in the DeviceRepository, where we pass the current_user.get_id()

1c1cfdc2e1789ce0386ec0844744d427725b45cc

2024-11-16 14:36 UTC, EduKav1813 commented
@not7cd Additionally, since you are much more experienced with Mikrotik, I would like to ask you to review the structure of the settings templates: `whois/settings/settings_template.py`. I suspect that there may be some settings in one class that may belong to the other, and while it does not makes significant practical difference, organizing them properly would help people with less domain knowledge on this matter.

2024-11-30 17:56 UTC, EduKav1813 commented
@oneacik As we agreed, added you as a reviewer

2025-01-02 20:10 UTC, merged